### ISSUE TITLE
List-syntax in config-files differs between python interpreters

### ISSUE THREAD

**Issue by ghost** [covid19-bh-biostats/seir#20]
**Describe the bug**
Python interpreter (PyCharm Community py3.6) could not understand the syntax like:

```
population =
    871036,
    3422996,
    1231274
```

**To Reproduce**
Python interpreter (PyCharm Community py3.6) could not understand the syntax like:
```
population =
    871036,
    3422996,
    1231274
```
Instead, is it possible to code like
```
population = [871036, 3422996, 1231274]
```

**System [please complete the following information]:**
PyCharm Community py3.6

Report from @Brelgaven

**Comment by ghost** [comment]
`population = [871036, 3422996, 1231274] `
should actually not work, but 
`population = 871036, 3422996, 1231274`
should work.

**Comment by guneytombak** [comment]
Thank you for your reply!
